accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from unicodedata import name
from django.urls import path
from receipts.views import (
    AccountCreateView,
    AccountListView,
    ExpenseCategoryCreate,
    ExpenseCategoryListView,
    ReceiptCreateView,
    ReceiptListView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path(
        "categories/create/",
        ExpenseCategoryCreate.as_view(),
        name="expense_category_create",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="account_create"
    ),
    path(
        "categories/", ExpenseCategoryListView.as_view(), name="expense_list"
    ),
    path("accounts/", AccountListView.as_view(), name="accounts_list"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models

from django.conf import settings

User_auth = settings.AUTH_USER_MODEL

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User_auth, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User_auth, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField(auto_now=False)
    purchaser = models.ForeignKey(
        User_auth, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account", related_name="receipts", on_delete=models.CASCADE, null=True
    )

    def __str__(self):
        return str(self.vendor) + str(self.date)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid:
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home/")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from receipts.models import ExpenseCategory, Account, Receipt

# Create your views here.


class ReceiptListView(LoginRequiredMixin, TemplateView):
    template_name = "receipts/list.html"
    model = Receipt

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ExpenseCategoryCreate(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "receipts/new.html"
    fields = ["name"]

    def form_valid(self, form):
        expense = form.save(commit=False)
        expense.owner = self.request.user
        expense.save()
        return redirect("expenses_list")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "receipts/new.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        account = form.save(commit=False)
        account.owner = self.request.user
        account.save()
        return redirect("accounts_list")


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/new.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        receipt = form.save(commit=False)
        receipt.purchaser = self.request.user
        receipt.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expenses/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

accounts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Expenses</title>
  </head>

  <body>
    <header>
      <nav>
        <ul id="navBar">
          <li>
          <a href="{% url 'home' %}">Home</a>
          </li>
          {% if user.is_staff %}
          <li>
            <a href="{% url 'admin' %">Admin</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li>
          <li>
            <a href="{% url 'receipt_create' %}">Add a Receipt</a>
          </li>
          <li>
            <a href="{% url 'account_create' %}">Create New Account</a>
          </li>
          <li>
            <a href="{% url 'accounts_list' %}">Accounts List</a>
          </li>
          <li>
            <a href="{% url 'expense_list' %}">Expenses List</a>
          </li>
          {% else %} 
          <li>
            <a href="{% url 'signup' %}">Sign Up</a>
          </li>
          <li>
            <a href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% block pagination %} {% endblock pagination %}
    </header>
    {% block content %} {% endblock content %}
  </body>
</html>

receipts/templates/accounts/list.html
{% extends 'base.html' %} 

{% block content %}
<h2>Accounts</h2>
<main>
  <table>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Number of Receipts</th>
    </tr>
    {% for acct in account_list %}
    <tr>
      <td>{{ account.name }}</td>
      <td>{{ account.number }}</td>
      <td>{{ receipts.count }}</td>
    </tr>
    {% endfor %}
  </table>
</main>
{% endblock content %}

receipts/templates/expenses/list.html
{% extends 'base.html' %} 

{% block content %}
<h2>Expenses Categories</h2>
<main>
    <table>
        <tr>
            <th>Name</th>
            <th>Number of receipts</th>
        </tr>
        {% for category in expensecategory_list %}
        <tr>
            <th>{{ expensecategory.name }}</th>
            <th>{{ receipts.count }}</th>
        </tr>
        {% endfor %}


</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% block content %}
<main>
  <table>
    <tr>
      <th>Vendor</th>
      <th>Total</th>
      <th>Tax</th>
      <th>Date</th>
      <th>Category</th>
      <th>Account</th>
    </tr>
    {% for item in receipt_list %}
    <tr>
      <td>{{ receipt.vendor }}</td>
      <td>{{ receipt.total }}</td>
      <td>{{ receipt.tax }}</td>
      <td>{{ receipt.date }}</td>
      <td>{{ receipt.category }}</td>
      {% if receipt.account %}
      <td>{{ receipt.account }}</td>
      {% else %}
      <td>Cash</td>
      {% endif %}
    </tr>
    {% endfor %}
  </table>
</main>
{% endblock content %}

receipts/templates/receipts/new.html
{% extends 'base.html' %}

{% block content %}
<h2>Create</h2>
<form method="post">
    {% csrf_token %}
    {{form.as_p }}
    <button>Submit</button>
</form>
{% endblock content %}